### ISSUE TITLE
Proposal to add @⌛ shortcut

### ISSUE THREAD

**Issue by marius311** [KristofferC/TimerOutputs.jl#106]
I just wanted to ask before maybe cleaning this up for a proper PR. 

This package is great, but one minor incovenience is labeling all your timed lines, and also the fact that it can be quite verbose so your code doesn't read as cleanly afterwards (assuming you want to leave the timers in there permanently). This tiny wrapper macro solves both of those things. From its docs:

```julia

    @⌛ code ...
    @⌛ function_definition() = .... 

Label a section of code to be timed. The first form uses the code
itselfs as a label, the second uses the function name, and its the
body of the function which is timed. 

To run the timer and print output, returning the result of the
calculation, use

    @show⌛ run_code()

Timing uses `TimerOutputs.get_defaulttimer()`. 
```

Let me know if you're interested in a PR, but also feel free to pass. Entire code below. Unicode chosen [democratically](https://twitter.com/cosmic_mar/status/1339298839891623936) via Slack :) 

<details/>

```julia
macro ⌛(ex)
    source_str = last(splitpath(string(__source__.file)))*":"*string(__source__.line)
    if _isdef(ex)
        sdef = splitdef(ex)
        sdef[:body] = quote
            @timeit $("$(string(sdef[:name]))(…)  ($source_str)") $(sdef[:body])
        end
        esc(combinedef(sdef))
    else
        :(@timeit $("$(Base._truncate_at_width_or_chars(string(prewalk(rmlines,ex)),26))  ($source_str)") $(esc(ex)))
    end
end


macro show⌛(ex)
    quote
        reset_timer!(get_defaulttimer())
        result = $(esc(ex))
        show(get_defaulttimer())
        result
    end
end
```

**Comment by KristofferC** [comment]
While cute, I feel that this is something you can quite easily make your own little wrapper for if you have the need.
