### ISSUE TITLE
`to(f)` syntax to instrument a function?

### ISSUE THREAD

**Issue by ericphanson** [KristofferC/TimerOutputs.jl#108]
In [TrackingTimers.jl](https://github.com/ericphanson/TrackingTimers.jl), I came up with a syntax that's been pretty useful and I think it could be useful in TimerOutputs too: making TimerOutputs a callable type that when acting on a function, "instrument" that function so that calls to it populate the timer. E.g.
```julia
using TimerOutputs

to = TimerOutput()
f(x) = x + 1
g = to(f) # InstrumentedFunction
g(1) # returns 6, populates `to`
```
The whole implementation is very short:

https://github.com/ericphanson/TrackingTimers.jl/blob/7d475005ce0293f704fac986392982a3fd1a8f41/src/TrackingTimers.jl#L142-L168

Would a PR here for that functionality be accepted?

**Comment by KristofferC** [comment]
Seems like a pretty good feature.
