### ISSUE TITLE
Saving TimerOutput to file

### ISSUE THREAD

**Issue by anandijain** [KristofferC/TimerOutputs.jl#112]
Hello, thanks for this package.

I'm wondering what the recommended way to write a TimerOutput to a human and computer readable file is.

I saw a closed issue about exporting to DataFrame. I don't think I'll need anything that heavy.

It looks like I can just use `show(io, to)` but I didn't see anything in the readme for this, so just wanted to ask. 

This way would also be only human readable I think.

**Comment by KristofferC** [comment]
For just writing the pretty printed version then just calling e.g `print_timer` or `show` to a file IO is indeed the way to do it.

**Comment by KristofferC** [comment]
You can just use the Serialization standard library to write arbitrary julia types to a file and reload them in another Julia session if that is what yiu want.
