### ISSUE TITLE
Explanation for making TimerOutput a const in readme?

### ISSUE THREAD

**Issue by anandijain** [KristofferC/TimerOutputs.jl#113]
Sorry for the spam Kristoffer,

I noticed the readme makes the `to` a const. There doesn't seem to be an explanation for this and I'm wondering if this is something I need to do in my code as well.

Thanks

**Comment by KristofferC** [comment]
Usually making global variables const if possible is a good idea. It allows julia to generate better code and it shows intent that the variable won't be rebound to another object.
