### ISSUE TITLE
prettytime limit for switching from seconds to minutes

### ISSUE THREAD

**Issue by jaakkor2** [KristofferC/TimerOutputs.jl#148]
https://github.com/KristofferC/TimerOutputs.jl/pull/146 added minute and hour for elapsed time units.  Switching from seconds to minutes at 60 seconds is too early in my opinionated view.

As an example, consider this example
```
────────────────────────────────────
                   Time             
          ───────────────────────   
               2.82m /  99.4%       
                                    
  ncalls     time    %tot     avg   
────────────────────────────────────
       1    1.16m   41.6%   1.16m   
       1    44.3s   26.4%   44.3s   
       1    25.1s   14.9%   25.1s   
       1    6.83s    4.1%   6.83s   
```
`1.16m` is about 70 s, `2.82m` is about 169 s, for these small numbers writing the elapsed time in seconds would be clearer (for me, at least).  Maybe the limit for the transition from seconds to minutes could be 500 s ?  I tried a quick internet search, but that did not return any good advice.

Also, symbol `m` for minute is a bit obscure. https://physics.nist.gov/cuu/Units/outside.html defines the symbol of minute as `min`.

**Comment by KristofferC** [comment]
Yeah, I agree. `1.16m` does not look nice at all. I think the motivation in https://github.com/KristofferC/TimerOutputs.jl/pull/146 was for very long times. I'm ok with just skipping minutes completely and go over to hours when time > 3600 s. What do you think about that?

**Comment by jaakkor2** [comment]
> Yeah, I agree. `1.16m` does not look nice at all. I think the motivation in #146 was for very long times. I'm ok with just skipping minutes completely and go over to hours when time > 3600 s. What do you think about that?

Sounds good to me.
