### ISSUE TITLE
Meta Issue: Please make more awareness for this package!

### ISSUE THREAD

**Issue by AhmedSalih3d** [KristofferC/TimerOutputs.jl#161]
This is really a great package and I just found it today - already I love it so much :) !

I don't know how I missed out on it but I've been using FlameGraphs, Benchmarking tools etc. and never once was this mentioned somewhere.

I am just "unlucky" that it skipped my attention for the last few years?

Kind regards

**Comment by KristofferC** [comment]
Tell your friends ;)
