### ISSUE TITLE
Percentages are not summing up to upper level: 29+29+15 = 100

### ISSUE THREAD

**Issue by ahojukka5** [KristofferC/TimerOutputs.jl#28]
Hi,

http://juliafem.org/performance/2017-08-13-eigenvalue-analysis-of-eiffel-tower-using-juliafem-0.3.2.html

It took actually a little bit of time to figure out that percentages and times are not summing up to upper level. I'm not sure is this actually a *bug*, but kind of confusing anyway. It would be nice to have something like automatically calculated "other, unexplained", so that numbers actually sum up to the upper level. Feel free to close issue if you think this is wanted behavior.

**Comment by KristofferC** [comment]
Timings are relative to the total time (which it why it says `%tot`). If there are sections of the code that you are not measuring then they won't add up to 100%. I think adding an extra section to each nested block would be a bit annoying.
