### ISSUE TITLE
runtime labels

### ISSUE THREAD

**Issue by denizyuret** [KristofferC/TimerOutputs.jl#29]
Hi Kristoffer: I would like to use labels computed at runtime, e.g. that depend on the value of a runtime variable. I was happy to see that using variables or expressions in @timeit works.  However it doesn't seem to collect all the records with the same string under the same entry.  Is there an easy fix?

**Comment by denizyuret** [comment]
I think flatten helps. I still don't understand why we get a very deep call hierarchy with runtime labels. Shouldn't identical string labels accumulate in one entry?

**Comment by fredrikekre** [comment]
Do you have an example?

**Comment by KristofferC** [comment]
As it is right now, identical sections will "collect" if they have the same parent. Otherwise they nest. I don't think this has anything to do with if the runtime label is a literal string or a variable.

From the README:

```
# Nested sections (sections with same name are not accumulated
# if they have different parents)
function time_test()
    @timeit to "nest 1" begin
        sleep(0.1)
        # 3 calls to the same label
        @timeit to "level 2.1" sleep(0.03)
        @timeit to "level 2.1" sleep(0.03)
        @timeit to "level 2.1" sleep(0.03)
        @timeit to "level 2.2" sleep(0.2)
    end
    @timeit to "nest 2" begin
        @timeit to "level 2.1" sleep(0.3)
        @timeit to "level 2.2" sleep(0.4)
    end
end
```

**Comment by denizyuret** [comment]
How is parenthood determined?  Lexical or dynamic scope?

**Comment by KristofferC** [comment]
Dynamic. I could perhaps add an option that ignores any nesting. Should be equal to calling flatten in the end but if the tree grows too deep, perhaps there are performance issues.

**Comment by denizyuret** [comment]
OK, the problem was I had a block with a return statement as an argument to the @timeit macro.  This messes up the "call hierarchy" and results in a deep tree. When I take the return out of the block it is all good. Here is a small example:
```
function foo(x)
    @timeit "foo" begin
        a = x*x
        return a
    end
end

function bar()
    @timeit "bar" a = foo(10)
    @timeit "bar" b = foo(10)
    @timeit "bar" c = foo(10)
end

reset_timer!()
bar()
print_timer()

 ────────────────────────────────────────────────────────────────────
                             Time                   Allocations
                     ──────────────────────   ───────────────────────
  Tot / % measured:      35.6ms / 0.00%            340KiB / 0.25%

 Section     ncalls     time   %tot     avg     alloc   %tot      avg
 ────────────────────────────────────────────────────────────────────
 bar              1   1.08μs   100%  1.08μs         -  100%         -
   bar            1    754ns  69.8%   754ns         -  100%         -
     bar          1   8.59μs   796%  8.59μs         -  100%         -
       foo        0   0.00ns  0.00%    NaNs         -  0.00%        -
     foo          0   0.00ns  0.00%    NaNs         -  0.00%        -
   foo            0   0.00ns  0.00%    NaNs         -  0.00%        -
 ────────────────────────────────────────────────────────────────────

```

**Comment by KristofferC** [comment]
You can use the `do`syntax if you want to support returns or exceptions, see README:

```
# a function version with `do` syntax for exception safety
function i_will_throw()
    timeit(to, "throwing") do
        sleep(0.5)
        throw(error("this is fine..."))
        print("nope")
    end
end
```
