### ISSUE TITLE
Feature Request: track "throughput"

### ISSUE THREAD

**Issue by staticfloat** [KristofferC/TimerOutputs.jl#47]
Often times wall-clock time isn't what I want to measure; I want to measure things like "throughput".  This is especially useful when working on code that mixes a lot of parallelized and non-parallelized portions, as it becomes much more difficult to know what a "good" number is when measuring wall-clock time.  Throughput can be easier to estimate what a "good" result would be.

I'm thinking a useful API could be something like `@timeit inputs=(B, C) outputs=A do_work!(A, B, C)` where the `@timeit` macro will look at the sizes and estimate data-in/data-out statistics over time, showing the overall "throughput" of the operation.  Tying the statistics together into time per byte of input/output can show inefficient (yet fast) operations pretty easily.

**Comment by KristofferC** [comment]
I have decided this is out of scope for this package :)
