### ISSUE TITLE
Disabling timing

### ISSUE THREAD

**Issue by staticfloat** [KristofferC/TimerOutputs.jl#49]
Timing doesn't add much overhead, but it is a little bit.  It would be neat to have a compile-time switch for `@timeit` that does nothing unless a package has been loaded in `debug mode` or somesuch.  As an example, I like to instrument NNlib with timer outputs, but it's kind of a pain to reinstrument every time I come back for another round of performance tweaks.  On the other hand, I don't really want to be calling clock functions and allocating memory when I don't have to.

One way I've thought of doing this is to use `@requires` to conditionally define `NNlib.to`, then write a wrapper macro for `@timeit` that checks `if isdefined(NNlib.to)` before emitting an actual `@timeit` block.  What do you think would be the best way to do this?

**Comment by KristofferC** [comment]
There is some discussion about it in the readme https://github.com/KristofferC/TimerOutputs.jl/blob/master/README.md#overhead. Is that a good enough solution?

**Comment by staticfloat** [comment]
I was hoping for an "officially blessed" solution; something like a `@timeit_debug` macro that wraps all executions in a conditional that checks dependent method or something.  Something like:

```
macro timeit_debug(ex)
    quote
        if TimerOutputs.timeit_debug_enabled()
            @timeit ex
        else
            nothing
        end
    end
end
```

Then you could expose a `TimerOutputs.enable_debug_timings()` that runs `Core.eval(TimerOutputs, :(timeit_debug_enabled() = true)`, and triggers recompilation for all affected methods.  This is the best idea I have, what do you think?

**Comment by staticfloat** [comment]
I tried something similar out, and it works pretty well.  PR with included demo: https://github.com/KristofferC/TimerOutputs.jl/pull/50

**Comment by dm3** [comment]
Is it possible to get a release with this functionality given that it's merged now or is it still under consideration?

**Comment by KristofferC** [comment]
There is already a release with this: https://github.com/KristofferC/TimerOutputs.jl/releases/tag/v0.5.0
