### ISSUE TITLE
Problems with Int32 keyword argument

### ISSUE THREAD

**Issue by dmaldona** [KristofferC/TimerOutputs.jl#54]
Using timersOutputs:

```
@timeit timeroutput "go_initvalues" begin
init_vals = go_initvalues(params)
end
```

This works if the function signature is:

`go_initvalues(params::GoParams; ctg_idx=-1)::GoInitValues
`
also works if the function signature is:

`go_initvalues(params::GoParams; ctg_idx::Int64=-1)::GoInitValues
`
but if switch to Int32:

`function go_initvalues(params::GoParams; ctg_idx::Int32=-1)::GoInitValues`

then:

```
ERROR: LoadError: MethodError: no method matching #go_initvalues#459(::Int64, ::typeof(go_initvalues), ::GoParams)
Closest candidates are:
  #go_initvalues#459(::Int32, ::Any, ::GoParams) at /Users/dmaldona/Projects/GO-Challenge1/models/original/GoParams.jl:221
Stacktrace:
 [1] go_initvalues(::GoParams) at /Users/dmaldona/Projects/GO-Challenge1/models/original/GoParams.jl:221
 [2] macro expansion at /Users/dmaldona/Projects/GO-Challenge1/models/original/GoRun1.jl:106 [inlined]
```

**Comment by fredrikekre** [comment]
What made you think this is an issue with the TimerOutputs package? The problem can be reduced to
```
julia> f(;x::Int32 = 1) = x
f (generic function with 1 method)

julia> f()
ERROR: MethodError: no method matching #f#3(::Int64, ::typeof(f))
```
which happens because the literal `1` is of type `Int64` (on 64-bit systems).

**Comment by dmaldona** [comment]
Sorry. You're right. My mistake.
