### ISSUE TITLE
Support for multiprocessing programs

### ISSUE THREAD

**Issue by atbug** [KristofferC/TimerOutputs.jl#57]
Is there a canonical method to use this package in a multiprocessing program?

Naively, I would try to use different timers for different processes and then combine the results, but I don't see a function combining timers. Also, it would be a little bit inconvenient to explicitly collect the timers from different processes.

**Comment by KristofferC** [comment]
> Is there a canonical method to use this package in a multiprocessing program?

Currently no, but help to make it so would be appreciated.

**Comment by KristofferC** [comment]
Let's keep discussion in https://github.com/KristofferC/TimerOutputs.jl/issues/72
