### ISSUE TITLE
Confusing allocations

### ISSUE THREAD

**Issue by jw3126** [KristofferC/TimerOutputs.jl#59]
If timers are nested, one can get distracting allocations. This is confusing, since one has to think if reported allocations are due to profiler or original code.
```julia
using TimerOutputs

function doit(timer)
    @timeit timer "loop" for i in 1:10^6
        @timeit timer "inner" begin end
        @timeit timer "inner2" begin end
    end
    timer
end
    
doit(TimerOutput())
#  ───────────────────────────────────────────────────────────────────
#                             Time                   Allocations      
#                     ──────────────────────   ───────────────────────
#   Tot / % measured:      368ms / 86.6%           34.6MiB / 88.3%    
# 
#  Section    ncalls     time   %tot     avg     alloc   %tot      avg
#  ───────────────────────────────────────────────────────────────────
#  loop            1    319ms   100%   319ms   30.5MiB  100%   30.5MiB  <----- here
#    inner2    1.00M   62.0ms  19.4%  62.0ns     0.00B  0.00%    0.00B
#    inner     1.00M   56.2ms  17.6%  56.2ns     0.00B  0.00%    0.00B
```

**Comment by KristofferC** [comment]
Yeah, would be good to remove allocations from inner timers. Shouldn't be too hard with a self allocation field in each timer.

**Comment by jw3126** [comment]
I don't know the internals of the package. But it seems you know precisely whats happening. Can you point me to the loc where the allocation happens?

**Comment by KristofferC** [comment]
Here is one place:

https://github.com/KristofferC/TimerOutputs.jl/blob/7baa8709b7e03f1ad5ebbca711ff7a78ec2b1842/src/TimerOutput.jl#L65

**Comment by jw3126** [comment]
Out of curiosity, why is that line allocating and how did you find that out?

**Comment by KristofferC** [comment]
I'll be honest, I have no memory of writing that comment :D. My guess is that I found it by sprinkling some `@time` statements around. I don't know really why it allocates.

**Comment by jw3126** [comment]
I think I roughly get it. An object that references a heap allocated object must will itself be heap allocated (for GC reasons). So a closure that references a heap allocated object will itself be heap allocated.
```julia
function doit(s, n)
    f = () -> s
    for i in 1:n
        f = () -> s
    end
    return f
end

struct Immutable{X}
    x::X
end
struct Mutable{X}
    x::X
end
    
for x in [1, :a, "a", Immutable(1), Mutable(1), Immutable([1])]
    @show x
    doit(x, 1)
    @time doit(x, 10000)
end
```
```
x = 1
  0.000004 seconds (1 allocation: 16 bytes)
x = :a
  0.000051 seconds (10.00 k allocations: 156.266 KiB)
x = "a"
  0.000052 seconds (10.00 k allocations: 156.266 KiB)
x = Immutable{Int64}(1)
  0.000005 seconds (1 allocation: 16 bytes)
x = Mutable{Int64}(1)
  0.000004 seconds (1 allocation: 16 bytes)
x = Immutable{Array{Int64,1}}([1])
  0.000050 seconds (10.00 k allocations: 156.266 KiB)
```

**Comment by KristofferC** [comment]
Yeah, that makes sense since a closure implemented equivalent to a `struct` wrapping the arguments it closes over (with a call overload) so creating that struct will allocate for reasons you specified.
