### ISSUE TITLE
Export to DataFrame

### ISSUE THREAD

**Issue by matteoacrossi** [KristofferC/TimerOutputs.jl#73]
Is there a direct way to export the TimerOutput object to say, a `DataFrame` object from the [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) package, or any other sort of tabular data?

**Comment by KristofferC** [comment]
No, but you can just use the querying API: https://github.com/KristofferC/TimerOutputs.jl/blob/master/README.md#querying-data
