### ISSUE TITLE
Empty table if `print_timer` is called in project outside module that uses the global timer 

### ISSUE THREAD

**Issue by henriquebecker91** [KristofferC/TimerOutputs.jl#83]
This file ([timer_outputs_0_5_4_bug.tar.gz](https://github.com/KristofferC/TimerOutputs.jl/files/4493301/timer_outputs_0_5_4_bug.tar.gz)) has a small reproducer script. I found this error because my code began to give me completely empty tables the moment I updated to version 0.5.4 (having not changed anything related to TimerOutputs for some time now). I am not sure what exactly causes that (as I have zero experience with macros), but I suspect the first lines changed by [this commit](https://github.com/KristofferC/TimerOutputs.jl/commit/2ad55c0ffffbf820c6be1d7b4077499c53bfb79d). Also, maybe I have not understood how the package should work and this was expected, but as it was a sudden change from the last version, and was not announced anywhere, I do believe it is unintended.

**Comment by KristofferC** [comment]
Yeah, it wasn't meant to change anything. Thanks for the report, will look at it.

**Comment by henriquebecker91** [comment]
Thanks for the fast answer!

**Comment by KristofferC** [comment]
I believe https://github.com/KristofferC/TimerOutputs.jl/pull/84 should fix this.
