### ISSUE TITLE
Signature to time function under custom keyword

### ISSUE THREAD

**Issue by mfherbst** [KristofferC/TimerOutputs.jl#86]
Instead of producing ever growing depths of indention I find the syntax
```julia
@timeit timer function tester()
    body
end
```
extremely convenient. This is fine as long as `tester` does not have a generic name like `LinearAlgebra.mul!` or when specialising the same function for many different types. In such cases I would love to have the syntax
```julia
@timeit timer "Special Tester" function tester()
    body
end
```
supported with essentially the meaning
```julia
function tester()
    @timeit timer "Special Tester"  begin
        body
    end
end
```

Would it be possible to support the second syntax in TimerOutput as well?

Note: The second syntax is currently valid code, just it times the definition of the function rather than the call.

**Comment by KristofferC** [comment]
Makes sense to me

**Comment by KristofferC** [comment]
Try https://github.com/KristofferC/TimerOutputs.jl/pull/87.

**Comment by mfherbst** [comment]
Awesome! Thanks!
