### ISSUE TITLE
Option to display exclusive/inclusive times and/or export to flamegraph

### ISSUE THREAD

**Issue by NHDaly** [KristofferC/TimerOutputs.jl#90]
Hi! :)

First off, thanks -- this package is _such_ a nice interface for measuring exactly what we want to measure! 🙌 

----

When I was looking at these results, it occurs to me that they look quite a bit like essentially a user-space profile, and as such I would want to be able to print nodes with inclusive and exclusive time.

For example, in this result, here:

```julia
─────────────────────────────────────────────────────────────────────────────────────────────────
                                                          Time                   Allocations      
                                                  ──────────────────────   ───────────────────────
                 Tot / % measured:                     9.65s / 0.02%            887KiB / 30.7%    

 Section                                  ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────────────────────────────────
 MethodInstance for g(::Int64, ::Int64)        1   2.16ms   100%  2.16ms    273KiB  100%    273KiB
   MethodInstance for h(::Vector{Any})         1    766μs  35.5%   766μs    187KiB  68.7%   187KiB
     MethodInstance for i2(::Integer)          1    236μs  10.9%   236μs   42.6KiB  15.6%  42.6KiB
     MethodInstance for i(::Integer)           1    178μs  8.23%   178μs   42.6KiB  15.6%  42.6KiB
 ─────────────────────────────────────────────────────────────────────────────────────────────────
```

The _exclusive_ times would be:
```
 MethodInstance for g(::Int64, ::Int64)        1   1.39ms   64.5%
   MethodInstance for h(::Vector{Any})         1    352μs  16.2%
     MethodInstance for i2(::Integer)          1    236μs  10.9%
     MethodInstance for i(::Integer)           1    178μs  8.23%
```

This is useful because (in my case at least) it is the exclusive times that i'm interested in: I want to know which function is the most expensive to compile (i'm trying to measure per-method type inference), and these timings would allow me to construct essentially a profile that shows that in this case `g()` is itself both the most expensive _single_ contributor to my overall time, as well as containing the entire tree. In some cases, this might _not_ be the case. A single leaf might be responsible for almost all of the time of a large higher node, and that can get lost if you can only see the inclusive times.

--------------------

It would also be super amazing to be able to export this into a profile!!! For example, I might imagine the above to look something like this:

<img width="480" alt="Screen Shot 2020-09-16 at 5 22 02 PM" src="https://user-images.githubusercontent.com/1582097/93393817-270dcd00-f841-11ea-98bd-82c10127c3b8.png">

Am I missing anything about how this package is supposed to be used? Does it make sense to use it like this? :)
Thanks! :)

**Comment by KristofferC** [comment]
Both of these suggestions seem good to me.

**Comment by KristofferC** [comment]
I think the new Base inference makes this non critical.
