### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by ranocha** [KristofferC/TimerOutputs.jl#93]
I noticed that this repo still uses travic-ci.org, at least based on the badge in the README. travis-ci.org will be shut down at the end of the year, cf. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom. Hence, everything should be migrated to travis-ci.com.

**Comment by DilumAluthge** [comment]
Looking at a recent PR, looks like the CI is running on .com. See e.g. https://github.com/KristofferC/TimerOutputs.jl/pull/95

So just the README badge needs to be updated from .org to .com. Want to make a PR?

**Comment by ranocha** [comment]
I'll do that.
