### ISSUE TITLE
Unsatisfiable requirements detected for package DataFrames v0.19.3

### ISSUE THREAD

**Issue by abx78** [KristofferC/TimerOutputs.jl#97]
I am trying to add the package to my Project and I get this error:

(v1.1) pkg> add TimerOutputs
  Updating registry at 'C:\Program Files\ReSolver.DistributedJulia\depot\registries\General'
  Updating git-repo 'https://github.com/JuliaRegistries/General.git'
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.7] or uninstalled
 ├─restricted to versions 0.19.3 by an explicit requirement, leaving only versions 0.19.3
 └─restricted by compatibility requirements with ODBC [be6f12e9] to versions: [0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4] — no versions left
   └─ODBC [be6f12e9] log:
     ├─possible versions are: [0.7.0, 0.8.0-0.8.6, 0.9.0-0.9.1, 1.0.0-1.0.4] or uninstalled
     └─restricted to versions 0.8.1 by an explicit requirement, leaving only versions 0.8.1

This is my package status

(v1.1) pkg> st
    Status `C:\Program Files\ReSolver.DistributedJulia\depot\environments\v1.1\Project.toml`
  [336ed68f] CSV v0.4.3
  [a93c6f00] DataFrames v0.19.3
  [31c24e10] Distributions v0.18.0
  [7073ff75] IJulia v1.18.1
  [4138dd39] JLD v0.9.1
  [682c06a0] JSON v0.20.0
  [093fc24a] LightGraphs v1.2.0
  [2fda8390] LsqFit v0.6.0
  [e1d29d7a] Missings v0.4.0
  [49dea1ee] Nettle v0.4.0
  [be6f12e9] ODBC v0.8.1
  [9b87118b] PackageCompiler v0.6.3
  [e6cf234a] RandomNumbers v1.0.3

Any chance to upgrade it? Thanks

**Comment by KristofferC** [comment]
This package has no non-stdlib dependencies so it is not the culprit. I also suggest upgrading julia, 1.1 is quite old.
